In [9]:
import torch
from torch import nn

### Create an 4 × 4 orthogonal matrix U

In [15]:
U = torch.empty(4,4)
nn.init.orthogonal_(U)
U

tensor([[ 0.8600, -0.2316, -0.2136, -0.4015],
        [-0.3812, -0.1412, -0.8726, -0.2709],
        [-0.3333, -0.2597,  0.4346, -0.7953],
        [-0.0634, -0.9268,  0.0646,  0.3645]])

### U Transpose

In [16]:
U_t = torch.transpose(U,0,1)

### Verify that U · U T = U T · U = I
A = U · U T

B = U T · U

In [17]:
A = torch.matmul(U,U_t)
A

tensor([[1.0000e+00, 1.4901e-08, 0.0000e+00, 3.7253e-08],
        [1.4901e-08, 1.0000e+00, 0.0000e+00, 6.3330e-08],
        [0.0000e+00, 0.0000e+00, 1.0000e+00, 3.3528e-08],
        [3.7253e-08, 6.3330e-08, 3.3528e-08, 1.0000e+00]])

In [18]:
B = torch.matmul(U_t, U)
B

tensor([[ 1.0000e+00, -7.4506e-09, -2.9802e-08, -4.4703e-08],
        [-7.4506e-09,  1.0000e+00,  3.7253e-08,  2.9802e-08],
        [-2.9802e-08,  3.7253e-08,  1.0000e+00,  0.0000e+00],
        [-4.4703e-08,  2.9802e-08,  0.0000e+00,  1.0000e+00]])

In [19]:
I = torch.eye(4)
I

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

### Results
The torch.nn.init.orthogonal_() fills the input Tensor with a (semi) orthogonal matrix. Source: https://pytorch.org/docs/stable/nn.init.html . That is why we see numbers that are very close to zero in all the non-diagonal values. If we round the non-diagonal values of both A and B, we would get the Identity matrix.

In [21]:
A.round()

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [22]:
B.round()

tensor([[1., -0., -0., -0.],
        [-0., 1., 0., 0.],
        [-0., 0., 1., 0.],
        [-0., 0., 0., 1.]])